# Generated by Django 5.0.6 on 2024-05-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookss',
            name='author',
            field=models.TextField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='ebookss',
            name='category',
            field=models.TextField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='ebookss',
            name='pages',
            field=models.TextField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='ebookss',
            name='pdf',
            field=models.FileField(default='Test', upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='ebookss',
            name='summary',
            field=models.TextField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='ebookss',
            name='title',
            field=models.TextField(default='Test', max_length=100),
        ),
    ]
