# Generated by Django 4.2.2 on 2024-05-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ebookss_author_ebookss_category_ebookss_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookss',
            name='authid',
        ),
    ]
